In [29]:
import numpy as np

A = np.random.randint(1, 1000, size=(4,4))
B = np.random.randint(1, 1000, size=(4,4))
 
     
result = [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]
 

for i in range(len(A)):
 
    
    for j in range(len(B[0])):
 
        
        for k in range(len(B)):
            result[i][j] += A[i][k] * B[k][j]


print('A =',A)
print('B =', B)
print('Product:')
for r in result:
                print(r)


A = [[613 856 715 809]
 [936 248 520 904]
 [381 146 326 122]
 [209 521 833 122]]
B = [[372 989 313 599]
 [881 608 973 580]
 [183 245 742 589]
 [126 796 778 233]]
Product:
[1214951, 1945844, 2184689, 1473299]
[775744, 1923472, 1623424, 1221416]
[345388, 642559, 598119, 533339]
[704560, 824666, 1285352, 946434]
